const LogoCarouselData = [
  { src: "/images/College Logos/logo (1).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (2).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (3).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (4).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (5).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (6).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (7).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (8).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (9).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (10).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (11).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (12).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (13).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (14).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (15).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (16).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (17).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (18).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (19).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (20).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (21).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (22).PNG", alt: "University Logo" },
  { src: "/images/College Logos/logo (23).PNG", alt: "University Logo" },
];

export default LogoCarouselData;
